#! /usr/bin/python3
import os
import time
from waveshare_epd import epd2in13b_V2
from PIL import Image,ImageDraw,ImageFont

epd = epd2in13b_V2.EPD()
epd.init()
epd.Clear()
time.sleep(1)
font_file = '/home/pi/Downloads/fonts/Font.ttc'
font18 = ImageFont.truetype(font_file, 18)

def show(text):
  HBlackimage = Image.new('1', (epd.height, epd.width), 255)
  HRYimage = Image.new('1', (epd.height, epd.width), 255)
  drawblack = ImageDraw.Draw(HBlackimage)
  drawry = ImageDraw.Draw(HRYimage)
  drawblack.text((10, 0), text, font=font18, fill=0)
  epd.display(epd.getbuffer(HBlackimage), epd.getbuffer(HRYimage))
  time.sleep(2)


if __name__ == '__main__':
    import sys
    show(' '.join(sys.argv[1:]))


